name: 簡易版README生成

on:
  push:
    branches:
      - Senko
      - Shiro
      - Suzu
    paths:
      - '.github/workflows/**'
      - 'README_images/**'

permissions:
  contents: write

jobs:
  GenerateSimpleReadme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Generate simple readme
        working-directory: ./.github/workflows/
        run: python ./GenerateSimpleREADME.py
      - name: Check diff
        id: check_diff
        run: |
          git add -N --all
          git diff --exit-code
        continue-on-error: true
      - name: Commit and Push
        if: ${{ steps.check_diff.outcome == 'failure' }}
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add --all
          git commit -m '[GitHub Actions] ドキュメントの自動生成' -m '対象のコミット: ${{ github.sha }}'
          git push origin